// frontend/angular-app/src/app/components/course-list/course-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { CourseService } from '../../services/course.service';
import { StudentService } from '../../services/student.service';
import { EnrollmentService } from '../../services/enrollment.service';
import { Course } from '../../models/course.model';
import { Student } from '../../models/student.model';

@Component({
  selector: 'app-course-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './course-list.component.html',
  styleUrls: ['./course-list.component.css']
})
export class CourseListComponent implements OnInit {
  courses: Course[] = [];
  students: Student[] = [];
  showEnrollModal = false;
  selectedCourseForEnrollment: Course | null = null;
  selectedStudentId: number | null = null;

  constructor(
    private courseService: CourseService, 
    private studentService: StudentService,
    private enrollmentService: EnrollmentService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.loadCourses();
    this.loadStudents();
  }

  loadCourses(): void {
    this.courseService.getCourses().subscribe(data => {
      this.courses = data;
    });
  }

  loadStudents(): void {
    this.studentService.getStudents().subscribe(data => {
      this.students = data;
    });
  }

  addCourse(): void {
    this.router.navigate(['/add-course']);
  }

  editCourse(id: number): void {
    this.router.navigate(['/edit-course', id]);
  }

  deleteCourse(id: number): void {
    if (confirm('Are you sure you want to delete this course?')) {
      this.courseService.deleteCourse(id).subscribe(() => {
        this.loadCourses();
      });
    }
  }

  openEnrollModal(course: Course): void {
    this.selectedCourseForEnrollment = course;
    this.showEnrollModal = true;
    this.selectedStudentId = null;
  }

  closeEnrollModal(): void {
    this.showEnrollModal = false;
    this.selectedCourseForEnrollment = null;
  }

  confirmEnrollment(): void {
    if (this.selectedCourseForEnrollment && this.selectedStudentId) {
      this.enrollmentService.enrollStudent(this.selectedStudentId, this.selectedCourseForEnrollment.courseId!)
        .subscribe({
          next: () => {
            alert('Enrollment successful!');
            this.closeEnrollModal();
          },
          error: (err) => {
            console.error(err);
            alert('Enrollment failed.');
          }
        });
    }
  }

  getGradient(index: number): string {
    const gradients = [
      'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
      'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
      'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
      'linear-gradient(135deg, #30cfd0 0%, #330867 100%)'
    ];
    return gradients[index % gradients.length];
  }
}

<div class="container mt-4">
  <div style="background: white; border-radius: 1rem; padding: 1.5rem; margin-bottom: 2rem; box-shadow: 0 10px 30px rgba(0,0,0,0.2); display: flex; justify-content: space-between; align-items: center;">
    <h2 style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 2rem; font-weight: bold; margin: 0;">Available Courses</h2>
    <button (click)="addCourse()" style="padding: 0.8rem 1.5rem; background: linear-gradient(90deg, #10b981 0%, #059669 100%); color: white; border: none; border-radius: 0.5rem; font-weight: bold; cursor: pointer; display: flex; align-items: center; gap: 0.5rem; box-shadow: 0 4px 6px rgba(0,0,0,0.1); transition: all 0.3s;"
            onmouseover="this.style.transform='scale(1.05)'; this.style.boxShadow='0 6px 10px rgba(0,0,0,0.2)'"
            onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0 4px 6px rgba(0,0,0,0.1)'">
      Add Course
    </button>
  </div>
  
  <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 2rem;">
    <div *ngFor="let course of courses; let i = index" 
         [style.background]="getGradient(i)"
         style="border-radius: 1rem; padding: 2rem; color: white; box-shadow: 0 10px 30px rgba(0,0,0,0.3); transition: all 0.3s; cursor: pointer;"
         onmouseover="this.style.transform='scale(1.05)'; this.style.boxShadow='0 15px 40px rgba(0,0,0,0.4)'"
         onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0 10px 30px rgba(0,0,0,0.3)'">
      <h3 style="font-size: 1.5rem; font-weight: bold; margin-bottom: 1rem; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">{{ course.courseName }}</h3>
      <p style="margin-bottom: 1.5rem; color: rgba(255,255,255,0.9);">{{ course.description }}</p>
      <div style="background: rgba(255,255,255,0.2); backdrop-filter: blur(10px); border-radius: 0.75rem; padding: 1rem; margin-bottom: 1.5rem;">
        <p style="margin-bottom: 0.5rem; display: flex; align-items: center; gap: 0.5rem;">
          <strong>Duration:</strong> {{ course.duration }}
        </p>
        <p style="margin: 0; display: flex; align-items: center; gap: 0.5rem;">
          <strong>Fee:</strong> {{ course.fee | currency }}
        </p>
      </div>
      <div style="display: flex; gap: 1rem;">
        <button (click)="openEnrollModal(course)" 
                style="flex: 1; padding: 0.8rem; background: white; color: #667eea; border: none; border-radius: 0.5rem; font-weight: bold; cursor: pointer; transition: all 0.3s; box-shadow: 0 4px 6px rgba(0,0,0,0.1);"
                onmouseover="this.style.transform='scale(1.05)'"
                onmouseout="this.style.transform='scale(1)'">
          Enroll
        </button>
        <button (click)="editCourse(course.courseId!)" 
                style="flex: 1; padding: 0.8rem; background: rgba(255, 255, 255, 0.3); color: white; border: 1px solid white; border-radius: 0.5rem; font-weight: bold; cursor: pointer; transition: all 0.3s;"
                onmouseover="this.style.background='rgba(255, 255, 255, 0.5)'"
                onmouseout="this.style.background='rgba(255, 255, 255, 0.3)'">
          Edit
        </button>
        <button (click)="deleteCourse(course.courseId!)" 
                style="flex: 1; padding: 0.8rem; background: rgba(239, 68, 68, 0.8); color: white; border: none; border-radius: 0.5rem; font-weight: bold; cursor: pointer; transition: all 0.3s;"
                onmouseover="this.style.background='rgba(220, 38, 38, 1)'"
                onmouseout="this.style.background='rgba(239, 68, 68, 0.8)'">
          Delete
        </button>
      </div>
    </div>
  </div>

  <!-- Enrollment Modal -->
  <div *ngIf="showEnrollModal" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); display: flex; justify-content: center; align-items: center; z-index: 1000;">
    <div style="background: white; padding: 2rem; border-radius: 1rem; width: 400px; box-shadow: 0 10px 30px rgba(0,0,0,0.3);">
      <h3 style="margin-top: 0; margin-bottom: 1.5rem; font-size: 1.5rem; font-weight: bold; color: #4a5568;">Enroll in {{ selectedCourseForEnrollment?.courseName }}</h3>
      
      <div style="margin-bottom: 1.5rem;">
        <label style="display: block; margin-bottom: 0.5rem; font-weight: bold; color: #4a5568;">Select Student</label>
        <select [(ngModel)]="selectedStudentId" style="width: 100%; padding: 0.75rem; border: 2px solid #e2e8f0; border-radius: 0.5rem; font-size: 1rem;">
          <option [ngValue]="null">-- Select Student --</option>
          <option *ngFor="let student of students" [ngValue]="student.studentId">
            {{ student.fullName }}
          </option>
        </select>
      </div>

      <div style="display: flex; gap: 1rem;">
        <button (click)="confirmEnrollment()" [disabled]="!selectedStudentId"
                style="flex: 1; padding: 0.8rem; background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 0.5rem; font-weight: bold; cursor: pointer; transition: all 0.3s;"
                [style.opacity]="selectedStudentId ? '1' : '0.5'">
          Confirm
        </button>
        <button (click)="closeEnrollModal()" 
                style="flex: 1; padding: 0.8rem; background: #718096; color: white; border: none; border-radius: 0.5rem; font-weight: bold; cursor: pointer;">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

// frontend/react-app/src/components/CourseList.jsx
import React, { useEffect, useState } from 'react';

const CourseList = ({ token, onAddCourse, onEditCourse }) => {
  const [courses, setCourses] = useState([]);
  const [students, setStudents] = useState([]);
  const [showEnrollModal, setShowEnrollModal] = useState(false);
  const [selectedCourseId, setSelectedCourseId] = useState(null);
  const [selectedStudentId, setSelectedStudentId] = useState('');

  useEffect(() => {
    fetchCourses();
  }, []);

  const fetchCourses = async () => {
    try {
      const response = await fetch(import.meta.env.VITE_COURSE_API_URL, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      if (!response.ok) {
        if (response.status === 401 || response.status === 403) {
          console.error("Authentication failed");
        }
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const data = await response.json();
      setCourses(data);
    } catch (error) {
      console.error('Error fetching courses:', error);
    }
  };

  const fetchStudents = async () => {
    try {
      const response = await fetch(import.meta.env.VITE_STUDENT_API_URL, {
        headers: {
            'Authorization': `Bearer ${token}` 
        }
      });
      const data = await response.json();
      setStudents(data);
    } catch (error) {
      console.error('Error fetching students:', error);
    }
  };

  const openEnrollModal = (courseId) => {
    setSelectedCourseId(courseId);
    setShowEnrollModal(true);
    fetchStudents();
  };

  const closeEnrollModal = () => {
    setShowEnrollModal(false);
    setSelectedCourseId(null);
    setSelectedStudentId('');
  };

  const handleEnroll = async () => {
    if (!selectedStudentId) return;

    try {
      const enrollmentUrl = import.meta.env.VITE_COURSE_API_URL.replace('/courses', '/enrollments');
      await fetch(enrollmentUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          studentId: selectedStudentId,
          courseId: selectedCourseId
        })
      });
      alert('Enrollment successful!');
      closeEnrollModal();
    } catch (error) {
      console.error('Error enrolling student:', error);
      alert('Enrollment failed');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this course?')) {
      try {
        await fetch(`${import.meta.env.VITE_COURSE_API_URL}/${id}`, {
          method: 'DELETE',
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        fetchCourses();
      } catch (error) {
        console.error('Error deleting course:', error);
      }
    }
  };

  return (
    <div className="container mx-auto mt-4 px-4">
      <div className="bg-white rounded-2xl shadow-2xl p-6 mb-8 flex justify-between items-center">
        <h2 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">Available Courses</h2>
        <button 
          className="text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105 hover:shadow-xl flex items-center gap-2" 
          style={{ background: 'linear-gradient(90deg, #10b981 0%, #059669 100%)' }}
          onClick={onAddCourse}
        >
          Add Course
        </button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {courses.map((course, index) => {
          const gradients = [
            'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
            'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
            'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
            'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
            'linear-gradient(135deg, #30cfd0 0%, #330867 100%)'
          ];
          const gradient = gradients[index % gradients.length];
          
          return (
            <div 
              className="rounded-2xl shadow-2xl overflow-hidden transform transition-all duration-300 hover:scale-105 hover:shadow-3xl" 
              key={course.courseId}
              style={{ background: gradient }}
            >
              <div className="p-6 text-white">
                <h5 className="text-2xl font-bold mb-3" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.3)' }}>{course.courseName}</h5>
                <p className="mb-4 text-white/90">{course.description}</p>
                <div className="bg-white/20 backdrop-blur-sm rounded-lg p-4 mb-4">
                  <p className="text-sm mb-2 flex items-center gap-2">
                    <span className="font-bold">Duration:</span> {course.duration}
                  </p>
                  <p className="text-sm flex items-center gap-2">
                    <span className="font-bold">Fee:</span> ${course.fee}
                  </p>
                </div>
                <div className="flex gap-2">
                  <button 
                    className="flex-1 bg-white text-purple-600 hover:bg-purple-50 font-bold py-3 px-4 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-xl"
                    onClick={() => openEnrollModal(course.courseId)}
                  >
                    Enroll
                  </button>
                  <button 
                    className="flex-1 bg-white/30 hover:bg-white/50 text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 backdrop-blur-sm"
                    onClick={() => onEditCourse(course)}
                  >
                    Edit
                  </button>
                  <button 
                    className="flex-1 bg-red-500/80 hover:bg-red-500 text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 backdrop-blur-sm"
                    onClick={() => handleDelete(course.courseId)}
                  >
                    Delete
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {showEnrollModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-2xl p-8 max-w-md w-full mx-4 shadow-2xl">
            <h3 className="text-2xl font-bold mb-6 text-gray-800">Enroll Student</h3>
            <div className="mb-6">
              <label className="block text-gray-700 font-bold mb-2">Select Student</label>
              <select 
                className="w-full p-3 border-2 border-purple-200 rounded-lg focus:outline-none focus:border-purple-500"
                value={selectedStudentId}
                onChange={(e) => setSelectedStudentId(e.target.value)}
              >
                <option value="">-- Select Student --</option>
                {students.map(student => (
                  <option key={student.studentId} value={student.studentId}>
                    {student.fullName}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex gap-4">
              <button 
                className="flex-1 bg-gradient-to-r from-purple-600 to-indigo-600 text-white font-bold py-3 px-6 rounded-lg shadow-lg hover:shadow-xl transition-all disabled:opacity-50"
                onClick={handleEnroll}
                disabled={!selectedStudentId}
              >
                Confirm
              </button>
              <button 
                className="flex-1 bg-gray-200 text-gray-800 font-bold py-3 px-6 rounded-lg hover:bg-gray-300 transition-all"
                onClick={closeEnrollModal}
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CourseList;
