// frontend/angular-app/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username = '';
  password = '';
  error = '';

  constructor(private authService: AuthService, private router: Router) {}

  onSubmit() {
    this.authService.login({ username: this.username, password: this.password }).subscribe({
      next: () => {
        this.router.navigate(['/students']);
      },
      error: (err) => {
        this.error = 'Invalid credentials';
        console.error('Login error', err);
      }
    });
  }
}

<div class="login-container" style="display: flex; align-items: center; justify-content: center; min-height: 100vh; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
  <div class="login-box" style="background: white; padding: 3rem; border-radius: 1.5rem; box-shadow: 0 20px 60px rgba(0,0,0,0.3); width: 100%; max-width: 450px; transition: all 0.3s;">
    <div style="text-align: center; margin-bottom: 2rem;">
      <div style="font-size: 4rem; margin-bottom: 1rem;">🎓</div>
      <h2 style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 2rem; font-weight: bold; margin-bottom: 0.5rem;">Welcome Back!</h2>
      <p style="color: #6b7280;">Login to your account</p>
    </div>
    <div *ngIf="error" class="error-message" style="background: #fee2e2; color: #dc2626; padding: 0.75rem; border-radius: 0.5rem; margin-bottom: 1rem; text-align: center; font-weight: 600;">{{ error }}</div>
    <form (ngSubmit)="onSubmit()">
      <div class="form-group" style="margin-bottom: 1.5rem;">
        <label for="username" style="display: block; color: #374151; font-weight: 600; margin-bottom: 0.5rem;">Username</label>
        <input type="text" id="username" [(ngModel)]="username" name="username" required style="width: 100%; padding: 0.75rem 1rem; border: 2px solid #e5e7eb; border-radius: 0.5rem; font-size: 1rem; transition: all 0.3s;" onfocus="this.style.borderColor='#667eea'; this.style.boxShadow='0 0 0 3px rgba(102, 126, 234, 0.1)';" onblur="this.style.borderColor='#e5e7eb'; this.style.boxShadow='none';" placeholder="Enter your username">
      </div>
      <div class="form-group" style="margin-bottom: 2rem;">
        <label for="password" style="display: block; color: #374151; font-weight: 600; margin-bottom: 0.5rem;">Password</label>
        <input type="password" id="password" [(ngModel)]="password" name="password" required style="width: 100%; padding: 0.75rem 1rem; border: 2px solid #e5e7eb; border-radius: 0.5rem; font-size: 1rem; transition: all 0.3s;" onfocus="this.style.borderColor='#667eea'; this.style.boxShadow='0 0 0 3px rgba(102, 126, 234, 0.1)';" onblur="this.style.borderColor='#e5e7eb'; this.style.boxShadow='none';" placeholder="Enter your password">
      </div>
      <button type="submit" style="width: 100%; padding: 0.875rem; background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 0.5rem; font-size: 1rem; font-weight: bold; cursor: pointer; transition: all 0.3s; box-shadow: 0 4px 6px rgba(0,0,0,0.1);" onmouseover="this.style.transform='scale(1.05)'; this.style.boxShadow='0 10px 20px rgba(0,0,0,0.2)';" onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0 4px 6px rgba(0,0,0,0.1)';">Login</button>
    </form>
  </div>
</div>

// frontend/react-app/src/components/Login.jsx
import React, { useState } from 'react';

const Login = ({ onLogin }) => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await fetch(import.meta.env.VITE_AUTH_LOGIN_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password }),
      });

      if (response.ok) {
        const data = await response.json();
        // Assuming the token decodes to role, or we infer it. 
        // For simple production readiness we store the token.
        // We might parse JWT claims here but for now let's persist auth.
        const role = username === 'admin' ? 'Admin' : 'User'; // Configured in backend
        onLogin({ username, role, token: data.token });
      } else {
        alert('Invalid credentials');
      }
    } catch (error) {
       console.error("Login failed", error);
       alert("Login service unavailable");
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen" style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
      <div className="px-10 py-8 bg-white shadow-2xl rounded-2xl w-full max-w-md transform transition-all hover:scale-105 duration-300">
        <div className="text-center mb-6">
          <div className="text-6xl mb-3">🎓</div>
          <h3 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">Welcome Back!</h3>
          <p className="text-gray-600 mt-2">Login to your account</p>
        </div>
        <form onSubmit={handleSubmit}>
          <div className="space-y-4">
            <div>
              <label className="block text-gray-700 font-semibold mb-2" htmlFor="username">Username</label>
              <input
                type="text"
                placeholder="Enter your username"
                className="w-full px-4 py-3 border-2 border-purple-200 rounded-lg focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 transition-all"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                required
              />
            </div>
            <div>
              <label className="block text-gray-700 font-semibold mb-2" htmlFor="password">Password</label>
              <input
                type="password"
                placeholder="Enter your password"
                className="w-full px-4 py-3 border-2 border-purple-200 rounded-lg focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 transition-all"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
            <button 
              type="submit"
              className="w-full py-3 mt-6 text-white font-bold rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105 hover:shadow-xl"
              style={{ background: 'linear-gradient(90deg, #667eea 0%, #764ba2 100%)' }}
            >
              Login
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;
