// frontend/angular-app/src/app/components/student-form/student-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { StudentService } from '../../services/student.service';
import { Student } from '../../models/student.model';

@Component({
  selector: 'app-student-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './student-form.component.html',
  styleUrls: ['./student-form.component.css']
})
export class StudentFormComponent implements OnInit {
  studentForm: FormGroup;
  isEditMode = false;
  studentId?: number;

  constructor(
    private fb: FormBuilder,
    private studentService: StudentService,
    private route: ActivatedRoute,
    private router: Router
  ) {
    this.studentForm = this.fb.group({
      fullName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      dateOfBirth: ['', Validators.required],
      contactNumber: ['']
    });
  }

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.studentId = +id;
      this.studentService.getStudent(this.studentId).subscribe(student => {
        this.studentForm.patchValue({
          fullName: student.fullName,
          email: student.email,
          dateOfBirth: student.dateOfBirth.toString().split('T')[0], // Format for input type=date
          contactNumber: student.contactNumber
        });
      });
    }
  }

  onSubmit(): void {
    if (this.studentForm.valid) {
      const student: Student = {
        ...this.studentForm.value,
        studentId: this.isEditMode ? this.studentId : 0
      };

      if (this.isEditMode) {
        this.studentService.updateStudent(student).subscribe(() => {
          this.router.navigate(['/students']);
        });
      } else {
        this.studentService.createStudent(student).subscribe(() => {
          this.router.navigate(['/students']);
        });
      }
    }
  }
}

<div class="container mt-4" style="max-width: 800px;">
  <div style="background: white; border-radius: 1rem; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.2);">
    <div style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); padding: 1.5rem;">
      <h2 style="color: white; font-size: 2rem; font-weight: bold; margin: 0; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">
        {{ isEditMode ? 'Edit Student' : 'Add New Student' }}
      </h2>
    </div>
    <form [formGroup]="studentForm" (ngSubmit)="onSubmit()" style="padding: 2rem;">
      <div style="margin-bottom: 1.5rem;">
        <label for="fullName" style="display: block; color: #374151; font-weight: 600; margin-bottom: 0.5rem;">Full Name</label>
        <input type="text" id="fullName" formControlName="fullName" 
               style="width: 100%; padding: 0.75rem 1rem; border: 2px solid #e5e7eb; border-radius: 0.5rem; font-size: 1rem; transition: all 0.3s;"
               onfocus="this.style.borderColor='#667eea'; this.style.boxShadow='0 0 0 3px rgba(102, 126, 234, 0.1)'"
               onblur="this.style.borderColor='#e5e7eb'; this.style.boxShadow='none'"
               placeholder="Enter full name">
      </div>
      <div style="margin-bottom: 1.5rem;">
        <label for="email" style="display: block; color: #374151; font-weight: 600; margin-bottom: 0.5rem;">Email</label>
        <input type="email" id="email" formControlName="email" 
               style="width: 100%; padding: 0.75rem 1rem; border: 2px solid #e5e7eb; border-radius: 0.5rem; font-size: 1rem; transition: all 0.3s;"
               onfocus="this.style.borderColor='#667eea'; this.style.boxShadow='0 0 0 3px rgba(102, 126, 234, 0.1)'"
               onblur="this.style.borderColor='#e5e7eb'; this.style.boxShadow='none'"
               placeholder="Enter email address">
      </div>
      <div style="margin-bottom: 1.5rem;">
        <label for="dateOfBirth" style="display: block; color: #374151; font-weight: 600; margin-bottom: 0.5rem;">Date of Birth</label>
        <input type="date" id="dateOfBirth" formControlName="dateOfBirth" 
               style="width: 100%; padding: 0.75rem 1rem; border: 2px solid #e5e7eb; border-radius: 0.5rem; font-size: 1rem; transition: all 0.3s;"
               onfocus="this.style.borderColor='#667eea'; this.style.boxShadow='0 0 0 3px rgba(102, 126, 234, 0.1)'"
               onblur="this.style.borderColor='#e5e7eb'; this.style.boxShadow='none'">
      </div>
      <div style="margin-bottom: 2rem;">
        <label for="contactNumber" style="display: block; color: #374151; font-weight: 600; margin-bottom: 0.5rem;">Contact Number</label>
        <input type="text" id="contactNumber" formControlName="contactNumber" 
               style="width: 100%; padding: 0.75rem 1rem; border: 2px solid #e5e7eb; border-radius: 0.5rem; font-size: 1rem; transition: all 0.3s;"
               onfocus="this.style.borderColor='#667eea'; this.style.boxShadow='0 0 0 3px rgba(102, 126, 234, 0.1)'"
               onblur="this.style.borderColor='#e5e7eb'; this.style.boxShadow='none'"
               placeholder="Enter contact number">
      </div>
      <div style="display: flex; gap: 1rem;">
        <button type="submit" [disabled]="studentForm.invalid" 
                style="flex: 1; padding: 0.875rem; background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; border: none; border-radius: 0.5rem; font-weight: bold; cursor: pointer; transition: all 0.3s; box-shadow: 0 4px 6px rgba(0,0,0,0.1);"
                [style.opacity]="studentForm.invalid ? '0.5' : '1'"
                [style.cursor]="studentForm.invalid ? 'not-allowed' : 'pointer'"
                onmouseover="if(!this.disabled) { this.style.transform='scale(1.05)'; this.style.boxShadow='0 6px 10px rgba(0,0,0,0.2)'; }"
                onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0 4px 6px rgba(0,0,0,0.1)'">
          Save Student
        </button>
        <a routerLink="/students" 
           style="flex: 1; padding: 0.875rem; background: linear-gradient(90deg, #6b7280 0%, #4b5563 100%); color: white; border: none; border-radius: 0.5rem; font-weight: bold; text-decoration: none; text-align: center; cursor: pointer; transition: all 0.3s; box-shadow: 0 4px 6px rgba(0,0,0,0.1); display: flex; align-items: center; justify-content: center;"
           onmouseover="this.style.transform='scale(1.05)'; this.style.boxShadow='0 6px 10px rgba(0,0,0,0.2)'"
           onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0 4px 6px rgba(0,0,0,0.1)'">
          Cancel
        </a>
      </div>
    </form>
  </div>
</div>

// frontend/react-app/src/components/StudentForm.jsx
import React, { useState, useEffect } from 'react';

const StudentForm = ({ onCancel, onSave, token, studentToEdit }) => {
  const [student, setStudent] = useState({
    fullName: '',
    email: '',
    dateOfBirth: '',
    contactNumber: '',
  });

  useEffect(() => {
    if (studentToEdit) {
      setStudent({
        ...studentToEdit,
        dateOfBirth: studentToEdit.dateOfBirth.split('T')[0] // Format date for input
      });
    }
  }, [studentToEdit]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setStudent({ ...student, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const url = studentToEdit 
        ? `${import.meta.env.VITE_STUDENT_API_URL}/${studentToEdit.studentId}`
        : import.meta.env.VITE_STUDENT_API_URL;
      
      const method = studentToEdit ? 'PUT' : 'POST';

      await fetch(url, {
        method: method,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(student),
      });
      onSave();
    } catch (error) {
      console.error('Error saving student:', error);
    }
  };

  return (
    <div className="container mx-auto mt-8 max-w-2xl px-4">
      <div className="bg-white shadow-2xl rounded-2xl overflow-hidden">
        <div className="p-6" style={{ background: 'linear-gradient(90deg, #667eea 0%, #764ba2 100%)' }}>
          <h2 className="text-3xl font-bold text-white" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.3)' }}>
            {studentToEdit ? 'Edit Student' : 'Add New Student'}
          </h2>
        </div>
        <form onSubmit={handleSubmit} className="p-8">
          <div className="space-y-5">
            <div>
              <label className="block text-gray-700 text-sm font-bold mb-2">Full Name</label>
              <input
                type="text"
                className="w-full py-3 px-4 border-2 border-purple-200 rounded-lg focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 transition-all"
                name="fullName"
                placeholder="Enter full name"
                value={student.fullName}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-gray-700 text-sm font-bold mb-2">Email</label>
              <input
                type="email"
                className="w-full py-3 px-4 border-2 border-purple-200 rounded-lg focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 transition-all"
                name="email"
                placeholder="Enter email address"
                value={student.email}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-gray-700 text-sm font-bold mb-2">Date of Birth</label>
              <input
                type="date"
                className="w-full py-3 px-4 border-2 border-purple-200 rounded-lg focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 transition-all"
                name="dateOfBirth"
                value={student.dateOfBirth}
                onChange={handleChange}
                required
              />
            </div>
            <div>
              <label className="block text-gray-700 text-sm font-bold mb-2">Contact Number</label>
              <input
                type="text"
                className="w-full py-3 px-4 border-2 border-purple-200 rounded-lg focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 transition-all"
                name="contactNumber"
                placeholder="Enter contact number"
                value={student.contactNumber}
                onChange={handleChange}
              />
            </div>
          </div>
          <div className="flex gap-4 mt-8">
            <button 
              type="submit" 
              className="flex-1 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105 hover:shadow-xl"
              style={{ background: 'linear-gradient(90deg, #667eea 0%, #764ba2 100%)' }}
            >
              Save Student
            </button>
            <button
              type="button"
              className="flex-1 bg-gradient-to-r from-gray-500 to-gray-600 hover:from-gray-600 hover:to-gray-700 text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105 hover:shadow-xl"
              onClick={onCancel}
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default StudentForm;
