// frontend/react-app/src/components/StudentList.jsx
import React, { useEffect, useState } from 'react';

const StudentList = ({ onAddStudent, onEditStudent, token }) => {
  const [students, setStudents] = useState([]);

  useEffect(() => {
    fetchStudents();
  }, []);

  const fetchStudents = async () => {
    try {
      const response = await fetch(import.meta.env.VITE_STUDENT_API_URL, {
        headers: {
            'Authorization': `Bearer ${token}` 
        }
      });
      const data = await response.json();
      setStudents(data);
    } catch (error) {
      console.error('Error fetching students:', error);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this student?')) {
      try {
        await fetch(`${import.meta.env.VITE_STUDENT_API_URL}/${id}`, {
          method: 'DELETE',
          headers: {
            'Authorization': `Bearer ${token}`
          }
        });
        fetchStudents();
      } catch (error) {
        console.error('Error deleting student:', error);
      }
    }
  };

  return (
    <div className="container mx-auto p-4">
      <div className="bg-white rounded-2xl shadow-2xl p-6 mb-6">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">📚 Student List</h2>
          <button 
            className="text-white font-bold py-3 px-6 rounded-lg shadow-lg transition-all duration-300 transform hover:scale-105 hover:shadow-xl flex items-center gap-2" 
            style={{ background: 'linear-gradient(90deg, #10b981 0%, #059669 100%)' }}
            onClick={onAddStudent}
          >
            Add Student
          </button>
        </div>
      </div>
      <div className="overflow-x-auto bg-white shadow-2xl rounded-2xl">
        <table className="min-w-full leading-normal">
          <thead>
            <tr style={{ background: 'linear-gradient(90deg, #667eea 0%, #764ba2 100%)' }}>
              <th className="px-5 py-4 text-left text-sm font-bold text-white uppercase tracking-wider">ID</th>
              <th className="px-5 py-4 text-left text-sm font-bold text-white uppercase tracking-wider">Full Name</th>
              <th className="px-5 py-4 text-left text-sm font-bold text-white uppercase tracking-wider">Email</th>
              <th className="px-5 py-4 text-left text-sm font-bold text-white uppercase tracking-wider">Date of Birth</th>
              <th className="px-5 py-4 text-left text-sm font-bold text-white uppercase tracking-wider">Contact</th>
              <th className="px-5 py-4 text-left text-sm font-bold text-white uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody>
            {students.map((student, index) => (
              <tr 
                key={student.studentId} 
                className="hover:bg-purple-50 transition-all duration-200"
                style={{ backgroundColor: index % 2 === 0 ? '#ffffff' : '#f9fafb' }}
              >
                <td className="px-5 py-4 border-b border-purple-100 text-sm font-semibold text-purple-600">{student.studentId}</td>
                <td className="px-5 py-4 border-b border-purple-100 text-sm font-medium text-gray-800">{student.fullName}</td>
                <td className="px-5 py-4 border-b border-purple-100 text-sm text-gray-600">{student.email}</td>
                <td className="px-5 py-4 border-b border-purple-100 text-sm text-gray-600">{new Date(student.dateOfBirth).toLocaleDateString()}</td>
                <td className="px-5 py-4 border-b border-purple-100 text-sm text-gray-600">{student.contactNumber}</td>
                <td className="px-5 py-4 border-b border-purple-100 text-sm">
                  <div className="flex gap-2">
                    <button
                      className="bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white font-bold py-2 px-4 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-md hover:shadow-lg"
                      onClick={() => onEditStudent(student)}
                    >
                      Edit
                    </button>
                    <button
                      className="bg-gradient-to-r from-red-500 to-red-600 hover:from-red-600 hover:to-red-700 text-white font-bold py-2 px-4 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-md hover:shadow-lg"
                      onClick={() => handleDelete(student.studentId)}
                    >
                      Delete
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default StudentList;

// frontend/angular-app/src/app/components/student-list/student-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { StudentService } from '../../services/student.service';
import { Student } from '../../models/student.model';

@Component({
  selector: 'app-student-list',
  standalone: true,
  imports: [CommonModule, RouterModule, MatTableModule, MatButtonModule, MatIconModule],
  templateUrl: './student-list.component.html',
  styleUrls: ['./student-list.component.css']
})
export class StudentListComponent implements OnInit {
  students: Student[] = [];
  displayedColumns: string[] = ['studentId', 'fullName', 'email', 'dateOfBirth', 'contactNumber', 'actions'];

  constructor(private studentService: StudentService) { }


  ngOnInit(): void {
    this.loadStudents();
  }

  loadStudents(): void {
    this.studentService.getStudents().subscribe(data => {
      this.students = data;
    });
  }

  deleteStudent(id: number): void {
    if(confirm("Are you sure to delete this student?")) {
      this.studentService.deleteStudent(id).subscribe(() => {
        this.loadStudents();
      });
    }
  }
}

<div class="container mt-4">
  <div style="background: white; border-radius: 1rem; padding: 1.5rem; margin-bottom: 1.5rem; box-shadow: 0 10px 30px rgba(0,0,0,0.2); display: flex; justify-content: space-between; align-items: center;">
    <h2 style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 2rem; font-weight: bold; margin: 0;">Student List</h2>
    <a routerLink="/add-student" mat-raised-button style="background: linear-gradient(90deg, #10b981 0%, #059669 100%); color: white; padding: 0.75rem 1.5rem; border-radius: 0.5rem; text-decoration: none; font-weight: bold; box-shadow: 0 4px 6px rgba(0,0,0,0.1); transition: all 0.3s;">➕ Add Student</a>
  </div>
  
  <div style="background: white; border-radius: 1rem; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.2);">
    <table mat-table [dataSource]="students" class="mat-elevation-z8 w-full">

      <!-- ID Column -->
      <ng-container matColumnDef="studentId">
        <th mat-header-cell *matHeaderCellDef style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; font-weight: bold; padding: 1rem;">ID</th>
        <td mat-cell *matCellDef="let element" style="padding: 1rem; font-weight: 600; color: #667eea;"> {{element.studentId}} </td>
      </ng-container>

      <!-- Name Column -->
      <ng-container matColumnDef="fullName">
        <th mat-header-cell *matHeaderCellDef style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; font-weight: bold; padding: 1rem;">Full Name</th>
        <td mat-cell *matCellDef="let element" style="padding: 1rem; font-weight: 500; color: #1f2937;"> {{element.fullName}} </td>
      </ng-container>

      <!-- Email Column -->
      <ng-container matColumnDef="email">
        <th mat-header-cell *matHeaderCellDef style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; font-weight: bold; padding: 1rem;">Email</th>
        <td mat-cell *matCellDef="let element" style="padding: 1rem; color: #4b5563;"> {{element.email}} </td>
      </ng-container>

      <!-- DOB Column -->
      <ng-container matColumnDef="dateOfBirth">
        <th mat-header-cell *matHeaderCellDef style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; font-weight: bold; padding: 1rem;">Date of Birth</th>
        <td mat-cell *matCellDef="let element" style="padding: 1rem; color: #4b5563;"> {{element.dateOfBirth | date}} </td>
      </ng-container>

      <!-- Contact Column -->
      <ng-container matColumnDef="contactNumber">
        <th mat-header-cell *matHeaderCellDef style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; font-weight: bold; padding: 1rem;">Contact</th>
        <td mat-cell *matCellDef="let element" style="padding: 1rem; color: #4b5563;"> {{element.contactNumber}} </td>
      </ng-container>

      <!-- Actions Column -->
      <ng-container matColumnDef="actions">
        <th mat-header-cell *matHeaderCellDef style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; font-weight: bold; padding: 1rem;">Actions</th>
        <td mat-cell *matCellDef="let element" style="padding: 1rem;">
          <a [routerLink]="['/edit-student', element.studentId]" mat-button style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%); color: white; margin-right: 0.5rem; border-radius: 0.5rem; font-weight: 600;">Edit</a>
          <button mat-button (click)="deleteStudent(element.studentId)" style="background: linear-gradient(90deg, #ef4444 0%, #dc2626 100%); color: white; border-radius: 0.5rem; font-weight: 600;">Delete</button>
        </td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;" style="transition: all 0.2s;" onmouseover="this.style.backgroundColor='#f3f4f6'" onmouseout="this.style.backgroundColor='white'"></tr>
    </table>
  </div>
</div>
